name: Build and Deploy Payment Documentation

on:
  push:
    branches:
      - main  # Ganti jika branch utama berbeda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install jq (jika belum tersedia)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3. Gabungkan file JSON dari folder 'payment' dengan menambahkan field "id"
      - name: Merge JSON files with added id field into data.min.json
        run: |
          echo "Menggabungkan file-file JSON dari folder 'payment'..."
          for file in payment/*.json; do
            filename=$(basename "$file" .json)
            jq --arg id "$filename" '. + {id: $id}' "$file"
          done | jq -cs '.' > data.min.json
          echo "data.min.json berhasil dibuat."

      # 4. Buat folder public untuk file yang akan dideploy
      - name: Create public folder
        run: mkdir -p public

      # 5. Salin file-file statis ke folder public
      - name: Copy static assets to public folder
        run: |
          cp index.html index.js style.css data.min.json example.html public/

      # 6. Generate payment-instruction.js dengan menyematkan konten data.min.json
      - name: Generate payment-instruction.js with embedded JSON data
        run: |
          node -e "\
          const fs = require('fs'); \
          const templatePath = 'payment-instruction.js'; \
          const outputPath = 'public/payment-instruction.js'; \
          const template = fs.readFileSync(templatePath, 'utf8'); \
          const jsonData = fs.readFileSync('data.min.json', 'utf8'); \
          const replaced = template.replace('JSON_EMBED_HERE', jsonData); \
          fs.writeFileSync(outputPath, replaced); \
          console.log('payment-instruction.js berhasil digenerate dengan embedded JSON data');"

      # 7. Deploy folder public ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public