name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Install jq (jika belum tersedia)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Langkah 3: Proses file-file JSON
      - name: Process and merge JSON files with added id field
        run: |
          echo "Menggabungkan file-file JSON dari folder 'payment' dengan menambahkan field id..."
          # Untuk setiap file JSON di folder payment, ambil nama file (tanpa ekstensi)
          # dan tambahkan properti "id" ke objek JSON-nya.
          for file in payment/*.json; do
            filename=$(basename "$file" .json)
            jq --arg id "$filename" '. + {id: $id}' "$file"
          done | jq -cs '.' > data.min.json
          echo "File data.min.json berhasil dibuat."

      # Langkah 4: Salin file-file yang diperlukan ke folder publik
      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p public
          cp data.min.json public/data.json
          cp index.html index.js example.html style.css payment-instruction.js data.min.json public/

      # Langkah 5: Deploy ke GitHub Pages menggunakan action peaceiris
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public