name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # atau branch lain sesuai kebutuhan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # (Opsional) Pastikan jq terinstal
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Langkah 2: Gabungkan file JSON dari folder 'payment' ke data.min.json
      - name: Merge JSON files into data.min.json
        run: |
          echo "Menggabungkan file JSON dari folder 'payment'..."
          # Perintah berikut akan membaca semua file JSON di folder 'payment',
          # menggabungkannya menjadi satu array, dan mengeluarkan output dalam format compact (minified)
          jq -c -s . payment/*.json > data.min.json
          echo "File data.min.json berhasil dibuat."

      # Langkah 3: Salin file-file yang diperlukan ke folder publik
      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p public
          cp data.min.json public/data.json
          cp index.html index.js example.html style.css payment-instruction.js data.min.json public/

      # Langkah 4: Deploy ke GitHub Pages menggunakan action peaceiris
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public